# Configuration of Academic
# Documentation: https://sourcethemes.com/academic/
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

# Title of your site
title = "Julian Pawlowski"

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "https://julian.pawlowski.me/"

# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
copyright = "Â© {year} Julian Pawlowski"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-144239485-1"

############################
## Advanced options below ##
############################

# Name of Academic theme folder in `themes/`.
theme = "academic"

# Get last modified date for content from Git?
enableGitInfo = false

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = true
removePathAccents = true  # Workaround for https://github.com/gohugoio/hugo/issues/5687

paginate = 10  # Number of items per page in paginated lists.
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

enableRobotsTXT = true

[outputs]
  home = [ "HTML", "JSON", "Sitemap", "RSS", "ATOM" ]
  section = [ "HTML", "RSS", "ATOM" ]
  taxonomy = [ "HTML", "RSS", "ATOM" ]

[mediaTypes."application/manifest+json"]
  suffixes = ["webmanifest"]

[outputFormats.WebAppManifest]
  mediaType = "application/manifest+json"
  rel = "manifest"

[mediaTypes."application/atom+xml"]
  suffixes = ["xml"]

[outputFormats.Atom]
  mediaType = "application/atom+xml"
  baseName = "atom"
  isPlainText = false

[outputFormats.RSS]
  mediaType = "application/rss+xml"
  baseName = "rss"
  isPlainText = false

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  hrefTargetBlank = false  # `true` opens external links in a new tab. See https://github.com/gohugoio/hugo/issues/2424
	angledQuotes = false
	latexDashes = true
  extensions = ["backslashLineBreak"]

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  anchor = "smart"  # Anchor for cropping. Options include Smart and Center.

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"

[permalinks]
  post = "/:slug/"
  project = "/project/:slug/"
  publication = "/:slug/"
  talk = "/:slug/"
  categories = "/:slug/"
  publication_types = "/:slug/"
